version: "3.8"

services:
  mongo1:
    # image: mongo:7.0
    build: 
      context: .
      dockerfile: Dockerfile.mongo1
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017","--keyFile", "/data/configdb/mongo-keyfile"]
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # healthcheck:
    #   test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017',priority:1},{_id:1,host:'host.docker.internal:27018',priority:0.5},{_id:2,host:'host.docker.internal:27019',priority:0.5}]}) }" | mongosh --port 27017 --quiet
    #   interval: 5s
    #   timeout: 30s
    #   start_period: 0s
    #   retries: 30
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    depends_on:
      - mongo2
      - mongo3
    networks:
      - mongo_network

  mongo2:
    # image: mongo:7.0
    build: .
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018","--keyFile", "/data/configdb/mongo-keyfile"]
    ports:
      - 27018:27018
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"
    networks:
      - mongo_network

  mongo3:
    # image: mongo:7.0
    build: .
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019","--keyFile", "/data/configdb/mongo-keyfile"]
    ports:
      - 27019:27019
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      - "mongo3_data:/data/db"
      - "mongo3_config:/data/configdb"
    networks:
      - mongo_network

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:

networks:
  mongo_network:
    driver: bridge